name: anyway
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.4
  freezed_annotation: ^1.0.0
  json_annotation: ^4.4.0

  models:
    path: models

  cupertino_icons: ^1.0.2

  cached_network_image: ^3.2.0
  provider: ^6.0.1
  fl_chart: ^0.40.6
  weather: ^2.0.1
  swipe_cards: ^0.1.0
  lottie: ^1.2.1

  google_maps_flutter: ^2.0.6

  intl: ^0.17.0
  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^1.0.2+1
  build_runner: ^2.1.5
  json_serializable: ^6.1.1

  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/


#flutter pub run flutter_native_splash:create
#flutter pub run flutter_native_splash:remove
flutter_native_splash:
  color: "#ffffff"
  image: assets/img.png