name: models
description: модели и интерфейсы для их получения.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  hive_flutter: ^1.1.0
  dio: ^4.0.4
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.5
  hive_generator: ^1.1.1
  json_serializable: ^6.1.1
  freezed: ^1.1.0
